# Ноутбук для решения задач урока 2.2 - Pandas забудь про циклы!

In [64]:
import numpy as np
import pandas as pd

## Степы 4️⃣ и 7️⃣

In [65]:
# для тестирования шагов 4,7
path = 'https://raw.githubusercontent.com/a-milenkin/Competitive_Data_Science/main/data/driver_info.csv'
driver_info = pd.read_csv(path)

In [66]:
print(f"Чему равняется медиана возраста водителей? Округлите ответ до целого. {round(np.median(driver_info.age))}")
print(f"Какой минимальный рейтинг у водителя? (user_rating). Ответ округлите до первого знака после точки. {round(min(driver_info.user_rating), 1)}")
print(f"Какое самое частое число инцидентов у водителей? (user_time_accident). Укажите целое число. {round(driver_info.user_time_accident.value_counts().index[0], 1)}")
print(f"Сколько строк в датасете? {driver_info.shape[0]}")
print(f"Какой самый популярный пол? Введите число. {driver_info.sex.value_counts().index[0]}")

Чему равняется медиана возраста водителей? Округлите ответ до целого. 33
Какой минимальный рейтинг у водителя? (user_rating). Ответ округлите до первого знака после точки. 5.8
Какое самое частое число инцидентов у водителей? (user_time_accident). Укажите целое число. 6.0
Сколько строк в датасете? 15153
Какой самый популярный пол? Введите число. 0

## Степ 6️⃣: 🧠Сложная фильтрация

Задача:
- Соединить две таблицы вместе.
- Оставить только строки, где `rating` > 4 и `stop_times` равен 2, 3 или 5.
- В получившемся датафрейме оставить только те строки, где `car_id` не входит в список `car_black_list` и `user_id` входит в список `user_white_list`.
- Оставить только строки, где `index` чётное число (датафрейм проиндексирован целыми числами).
- Итоговый объект `pd.DataFrame()` поместить в переменную `result`.

In [67]:
df1 = pd.read_csv('https://stepik.org/media/attachments/lesson/681964/2.2.6_df1.csv', index_col=0)
df2 = pd.read_csv('https://stepik.org/media/attachments/lesson/681964/2.2.6_df2.csv', index_col=0)

# Учтите, что user_white_list и car_black_list в тестовой системе будут иметь другую длину и другие значения
user_white_list = ['g10995906g', 'H90312511Q', 'C27138482L', 'H22518078t', 'n17438464n', 'F10525768e', 's15596151o', 'i18954748S', 'E84048392U', 'E69893354s']
car_black_list = ['l-4285389z', 'n79502261g', 'N-1839822D']

In [68]:
res_df = pd.concat((df1, df2))

res_df = res_df[
    (res_df["rating"] > 4) &
    (res_df["stop_times"].isin((2, 3, 5)))
]

res_df = res_df[~(res_df["car_id"].isin(car_black_list)) & (res_df["user_id"].isin(user_white_list))]

result = res_df[(res_df.index % 2) == 0]

In [69]:
result

        user_id      car_id  rating  stop_times
20   C27138482L  M-1786506l    7.42           2
190  F10525768e  I98930031r    4.21           2
248  s15596151o  u-2070489i    5.39           2

In [70]:
# В ans содержится правильный ответ. Перед отправкой своего решения, сравнитесь с ним.
ans = pd.read_csv('https://stepik.org/media/attachments/lesson/681964/2_2_6_ans.csv', index_col=0)
ans

        user_id      car_id  rating  stop_times
20   C27138482L  M-1786506l    7.42           2
190  F10525768e  I98930031r    4.21           2
248  s15596151o  u-2070489i    5.39           2

## Степ 8️⃣: 🧠 Изменение и фильтрация `DataFrame` в Pandas
Задача:

- Создайте столбец `tripple_accident` из столбца `user_time_accident`,  умноженного на 3.
- Создайте столбец `rides_on_rating` делением столбца `user_rides` на `user_rating`.
- Оставьте только те строки, у которых `user_time_accident` больше 25 (используем фильтрацию).
- Оставьте только те строки, у которых `age` выше среднего значения по полученной таблице в предыдущем пункте.

In [71]:
df = pd.read_csv('https://stepik.org/media/attachments/lesson/681964/2_2_8.csv')

In [72]:
# Входные данные записаны в переменную df, проводим манипуляции с df.
df['tripple_accident'] = df['user_time_accident'] * 3
df['rides_on_rating'] = df['user_rides'] / df['user_rating']

filter_df = df.loc[(df['user_time_accident'] > 25)]
df = filter_df.loc[ (filter_df['age'] > filter_df['age'].median())]
df

,user_id,user_rating,age,user_rides,user_time_accident,tripple_accident,rides_on_rating
3,E10711310m,8.4,33,322,39.0,117.0,38.333333

In [73]:
# В ans содержится правильный ответ. Перед отправкой своего решения, сравнитесь с ним.
ans = pd.read_csv('https://stepik.org/media/attachments/lesson/681964/2_2_8_ans.csv', index_col=0)
ans

,user_id,user_rating,age,user_rides,user_time_accident,tripple_accident,rides_on_rating
3,E10711310m,8.4,33,322,39.0,117.0,38.333333
64,t25217963K,8.0,30,101,72.0,216.0,12.625000

## Степ 🔟: 🧠 Задача на работу с индексами и столбцами
Задача:

- Добавьте новую строку (с индексом `new_index:(int / str)` и значениями `new_data: list`).
- Удалите строки с индексами из списка `del_index_list: list`.
- Увеличьте значение `destroy_degree` на 1 в строке с индексом равным `index`. Переменная `index` содержит индекс строки ИЛИ число (индекс).
- Удалите столбец `fix_date`, т.к. не стоит сейчас думать о времени.
- Создайте новый столбец `efficient`, который равен `destroy_degree` деленный на `work_duration`.
- Возведите столбец `work_duration` в квадрат.
- Переименуйте столбец `work_duration` в `work_duration_square`.
- Удалите дубликаты по столбцу `car_id`.

In [74]:
df = pd.read_csv('https://stepik.org/media/attachments/lesson/681964/2_2_10.csv')

# Учтите, что new_index, new_data, del_index_list, index в тестовой системе будут иметь другие значения
new_index = 50
new_data = ['new_car_id', 'new_worker_id', '2019-11-11 4:44','refuel_check', 3.5, 10]
del_index_list = [41, 18, 33, 7, 46]
index = 22

In [75]:
df.loc[new_index] = new_data
df = df.drop(del_index_list, axis=0, errors='ignore')
df.loc[index, 'destroy_degree'] += 1
df = df.drop('fix_date', axis=1, errors='ignore')
df['efficient'] = df['destroy_degree'] / df['work_duration']
df['work_duration'] = df['work_duration'] ** 2
df = df.rename({'work_duration': 'work_duration_square'}, axis=1)
df = df.drop_duplicates(subset=['car_id'])
df.head()

,car_id,worker_id,work_type,destroy_degree,work_duration_square,efficient
0,C-8860661H,BM,reparking,1.0,784,0.035714
1,Z76775340d,IL,repair,8.4,2304,0.175000
2,r12485993Y,HN,reparking,1.0,441,0.047619
3,Z-1382353b,VX,repair,5.7,169,0.438462
4,p14707024B,JP,refuel_check,1.0,441,0.047619

In [76]:
# В ans содержится правильный ответ. Перед отправкой своего решения, сравнитесь с ним.
ans = pd.read_csv('https://stepik.org/media/attachments/lesson/681964/2_2_10_ans.csv')
ans.head()

,Unnamed: 0,car_id,worker_id,work_type,destroy_degree,work_duration_square,efficient
0,0,C-8860661H,BM,reparking,1.0,784,0.035714
1,1,Z76775340d,IL,repair,8.4,2304,0.175000
2,2,r12485993Y,HN,reparking,1.0,441,0.047619
3,3,Z-1382353b,VX,repair,5.7,169,0.438462
4,4,p14707024B,JP,refuel_check,1.0,441,0.047619

## Степ 1️⃣1️⃣: 🧠 Сортировка и фильтрация
Задача:

- Отсортируйте строки сначала по убывания 1-го столбца из списка `sort_by_list`, затем по возрастанию 2-го столбца из списка.
- Удалите столбцы из списка `cols2drop` с учетом того, что некоторых столбцов может не быть в df.
- Сделайте порядок столбцов в `df` в соответствии с переменной `columns_order_list: List[str]`.
- Удалите строки, в которых `car_rating` < `critical_car_rating`.
- Удалите строки, где число поездок `riders` больше `10_000`, или тип машины `car_type` относится либо к `standart`, либо `economy`.

In [77]:
df = pd.read_csv('https://stepik.org/media/attachments/lesson/681964/2.2.11.csv')

# Учтите, что sort_by_list, cols2drop, columns_order_list в тестовой системе будут иметь другие значения.
sort_by_list = ['car_rating', 'riders']
cols2drop = ['random_name_1', 'target_reg', 'target_class', 'random_name_2']
columns_order_list = ['model', 'car_type', 'car_id', 'car_rating', 'year_to_start', 'year_to_work', 'riders', 'fuel_type']
critical_car_rating = 2

In [78]:
new_df = (
    df
    .sort_values(by=sort_by_list[0], ascending=False)
    .sort_values(by=sort_by_list[1], ascending=True)
)

new_df = new_df.drop(columns=cols2drop, errors='ignore')
new_df = new_df[columns_order_list]
new_df = new_df[new_df['car_rating'] >= critical_car_rating]
new_df = new_df[
    (new_df["riders"] <= 10_000) &
    ~(new_df["car_type"].isin(["standart", "economy"]))
  ]

df = new_df.copy()
df

,model,car_type,car_id,car_rating,year_to_start,year_to_work,riders,fuel_type
4,Mini Cooper,business,i-4390733F,4.96,2012,2018,1007,petrol
295,Mini Cooper,business,b34607341j,4.04,2011,2018,2740,petrol

In [79]:
# В ans содержится правильный ответ. Перед отправкой своего решения, сравнитесь с ним.
ans = pd.read_csv('https://stepik.org/media/attachments/lesson/681964/2_2_11_ans.csv', index_col=0)
ans

,model,car_type,car_id,car_rating,year_to_start,year_to_work,riders,fuel_type
4,Mini Cooper,business,i-4390733F,4.96,2012,2018,1007,petrol
295,Mini Cooper,business,b34607341j,4.04,2011,2018,2740,petrol

## Степ 1️⃣2️⃣: 🧠 Задача на функции
Задача
- Запишите в переменную `mean_rating` среднее по столбцу `car_rating`.
- Увеличьте на один все значения в столбцах `car_rating` и `year_to_work`.
- Отфильтруйте любым из удобных способов машины с рейтингом выше среднего от столбца `car_rating` (используйте переменную `mean_rating`).
- Преобразуйте столбец `year_to_work` следующим образом: если значение меньше `2017`, то прибавьте `2`, иначе разделите значение нацело на `5`.
- Переименуйте столбец `year_to_start` в `new_year_to_start` и удалите столбец `fuel_type`.
- Ко всем значениям из столбца `car_type` добавьте приставку `super_` (`standart` -> `super_standart`).
- Решение запишите в переменную `result`.

In [80]:
df = pd.read_csv('https://stepik.org/media/attachments/lesson/681964/2_2_12.csv')

In [81]:
mean_rating = df["car_rating"].mean()

df["car_rating"] = df["car_rating"] + 1
df["year_to_work"] = df["year_to_work"] + 1

df = df[df["car_rating"] >= mean_rating]

df["year_to_work"] = df["year_to_work"].apply(lambda x: x + 2 if x < 2017 else x // 5)

df = (
    df
    .rename(columns={"year_to_start": "new_year_to_start"})
    .drop(columns="fuel_type", errors="ignore")
)

df["car_type"] = df["car_type"].apply(lambda x: "super_" + x)

result = df.copy()
result

,Unnamed: 0,car_id,model,car_type,car_rating,new_year_to_start,riders,year_to_work,target_reg,target_class
0,0,o-1588203t,VW Polo VI,super_economy,5.04,2014,61872,2018,46.175419,engine_check
1,1,B-1760099A,Renault Kaptur,super_standart,5.36,2015,95768,404,30.585652,engine_overheat
2,2,u-2045579o,Renault Kaptur,super_standart,6.94,2012,21114,404,68.091881,engine_ignition
3,3,V-4730687q,VW Tiguan,super_economy,5.10,2016,95799,403,39.808397,break_bug
4,4,K23027223e,Smart ForTwo,super_economy,4.82,2017,127971,404,37.024779,electro_bug
...,...,...,...,...,...,...,...,...,...,...
95,95,i22101695X,Fiat 500,super_business,6.16,2015,80937,404,54.714139,engine_check
96,96,a22370652k,Kia Rio,super_economy,5.56,2013,46108,404,31.320599,break_bug
97,97,H-1952766q,Tesla Model 3,super_premium,5.92,2014,58631,404,50.306346,gear_stick
98,98,r13675823Y,VW Polo VI,super_economy,5.36,2015,84108,403,34.150655,engine_fuel
99,99,I-1117298r,VW Tiguan,super_economy,5.54,2015,82807,404,111.275852,another_bug

In [82]:
# В ans содержится правильный ответ. Перед отправкой своего решения, сравнитесь с ним.
ans = pd.read_csv('https://stepik.org/media/attachments/lesson/681964/2_2_12_ans.csv')
ans

,Unnamed: 0,car_id,model,car_type,car_rating,new_year_to_start,riders,year_to_work,target_reg,target_class
0,0,o-1588203t,VW Polo VI,super_economy,5.04,2014,61872,2018,46.175419,engine_check
1,1,B-1760099A,Renault Kaptur,super_standart,5.36,2015,95768,404,30.585652,engine_overheat
2,2,u-2045579o,Renault Kaptur,super_standart,6.94,2012,21114,404,68.091881,engine_ignition
3,3,V-4730687q,VW Tiguan,super_economy,5.10,2016,95799,403,39.808397,break_bug
4,4,K23027223e,Smart ForTwo,super_economy,4.82,2017,127971,404,37.024779,electro_bug
...,...,...,...,...,...,...,...,...,...,...
85,95,i22101695X,Fiat 500,super_business,6.16,2015,80937,404,54.714139,engine_check
86,96,a22370652k,Kia Rio,super_economy,5.56,2013,46108,404,31.320599,break_bug
87,97,H-1952766q,Tesla Model 3,super_premium,5.92,2014,58631,404,50.306346,gear_stick
88,98,r13675823Y,VW Polo VI,super_economy,5.36,2015,84108,403,34.150655,engine_fuel
89,99,I-1117298r,VW Tiguan,super_economy,5.54,2015,82807,404,111.275852,another_bug

## Степ 1️⃣3️⃣: 🧠 Работа с функциями
Задача
- Добавьте столбец `flag`, который равен `'good_line'`, если `rating > 5` and `speed_max < 100`. `'bad_line'`, если  `rating > 5` and `speed_max > 100`. `'undefined'` в остальных случаях.
- Добавьте столбец `speed_check`, который принимает значения `'avg_more'`, если `distance/ride_duration > speed_avg`, иначе `'avg_less'`.
- Удалите столбцы из списка `cols2drop`.
- Удалите строки, в которых `car_id` имеет пустые значения (только NA удаляем).
- Результат запишите в переменную `result`.

In [83]:
df = pd.read_csv('https://stepik.org/media/attachments/lesson/681964/2_2_13.csv')

# Учтите, что cols2drop в тестовой системе будет иметь другие значения.
cols2drop = ['ride_cost', 'stop_times', 'user_ride_quality']

In [84]:
df["flag"] = df.apply(
    lambda x: "good_line"
    if x["rating"] > 5 and x["speed_max"] < 100
    else "bad_line" if x["rating"] > 5 and x["speed_max"] > 100
    else "undefined",
  axis=1)


df["speed_check"] = df.apply(
    lambda x: "avg_more"
    if x["distance"] / x["ride_duration"] > x["speed_avg"]
    else "avg_less",

axis=1)

df = df.drop(columns=cols2drop, errors="ignore")
df = df.dropna(subset=["car_id"])

result = df.copy()
result.head()

,user_id,car_id,ride_id,ride_date,rating,ride_duration,speed_avg,speed_max,distance,refueling,deviation_normal,flag,speed_check
0,Q57343968C,i-6289789v,F1u,2020-03-02,1.79,35,87,125.463335,2930.798145,0,-8.683,undefined,avg_less
1,N39662076X,F17991047v,J1A,2020-03-16,4.36,16,36,63.275887,472.946034,0,-37.196,undefined,avg_less
2,R39462885w,l36861534V,m1v,2020-01-20,2.20,5,47,73.000000,283.626484,0,3.378,undefined,avg_more
3,q32765597m,R16189354h,v1q,2020-02-24,2.82,10,31,76.838507,100.743738,0,14.758,undefined,avg_less
4,n30214850g,N-1839822D,p1h,2020-01-31,3.54,17,26,53.000000,268.451947,0,21.179,undefined,avg_less

In [85]:
# В ans содержится правильный ответ. Перед отправкой своего решения, сравнитесь с ним.
ans = pd.read_csv('https://stepik.org/media/attachments/lesson/681964/2_2_13_ans.csv', index_col=0)
ans.head()

,user_id,car_id,ride_id,ride_date,rating,ride_duration,speed_avg,speed_max,distance,refueling,deviation_normal,flag,speed_check
0,Q57343968C,i-6289789v,F1u,2020-03-02,1.79,35,87,125.463335,2930.798145,0,-8.683,undefined,avg_less
1,N39662076X,F17991047v,J1A,2020-03-16,4.36,16,36,63.275887,472.946034,0,-37.196,undefined,avg_less
2,R39462885w,l36861534V,m1v,2020-01-20,2.20,5,47,73.000000,283.626484,0,3.378,undefined,avg_more
3,q32765597m,R16189354h,v1q,2020-02-24,2.82,10,31,76.838507,100.743738,0,14.758,undefined,avg_less
4,n30214850g,N-1839822D,p1h,2020-01-31,3.54,17,26,53.000000,268.451947,0,21.179,undefined,avg_less

## Степ 1️⃣4️⃣: 🧠 Заполнение и редактирование таблиц
Задача
- Посчитайте количество пропусков в каждой строке и запишите это в новый столбец `nans_num`.
- Удалите строки, где количество пропусков больше `2`.
- Удалите строки, где `age` имеет пропущенные значения.
- Заполните пропущенные значения в столбце `user_time_accident` медианным значением.
- Оставьте только столбцы `age`, `user_rides`, `user_time_accident`.
- Решение запишите в переменную `result`.

In [86]:
df = pd.read_csv('https://stepik.org/media/attachments/lesson/681964/2_2_14.csv')

In [87]:
df["nans_num"] = df.isna().sum(axis=1)
df = df[df["nans_num"] <= 2]
df = df.dropna(subset=["age"])
df["user_time_accident"] = df["user_time_accident"].fillna(df["user_time_accident"].median())
df = df[["age", "user_rides", "user_time_accident"]]
result = df.copy()
result.head()

    age  user_rides  user_time_accident
0  36.0       907.0                10.0
1  32.0       343.0                15.0
3  32.0       852.0                 5.0
4  34.0       344.0                10.0
5  35.0      1124.0                 3.0

In [88]:
# В ans содержится правильный ответ. Перед отправкой своего решения, сравнитесь с ним.
ans = pd.read_csv('https://stepik.org/media/attachments/lesson/681964/2_2_14_ans.csv', index_col=0)
ans.head()

    age  user_rides  user_time_accident
0  36.0       907.0                10.0
1  32.0       343.0                15.0
3  32.0       852.0                 5.0
4  34.0       344.0                10.0
5  35.0      1124.0                 3.0