# Задача на 2-ом шаге урока

**🧠 Практика по apply() на 3 столбцах**

Датасет для тестирования:

Задание: Создайте в df новый столбец final_ride_cost, который будет зависеть от рейтинга (rating) и максимальной скорости (speed_max) поездки. Значения в этом столбце будут отличаться в зависимости от двух условий:
- Если рейтинг выше 6 и максимальная скорость поездки меньше 120 км/ч, то стоимость поездки (ride_cost) уменьшите на 5%.
- В противном случае: стоимость поездки (ride_cost) увеличьте на 5%.

В новом столбце final_ride_cost отбросьте дробную часть значений, оставьте только целую часть. Так как стоимость измеряется в рублях, дробная часть не имеет значения.

In [39]:
import pandas as pd

df = pd.read_csv('https://stepik.org/media/attachments/lesson/779916/3_1_2.csv')

# В столбце true_final_ride_cost записаны правильные ответы.
# Создайте столбец final_ride_cost исходя из условий задачи.

In [40]:
def final_ride_cost_func(data):
    if (data['rating'] > 6) and (data['speed_max'] < 120):
        return np.floor(data['ride_cost'] * 0.95).astype(int)
    else:
        return np.floor(data['ride_cost'] * 1.05).astype(int)
df['final_ride_cost'] = df.apply(final_ride_cost_func, axis=1)

In [41]:
# Корректность своего ответа можно проверить, например, таким образом
print(df['final_ride_cost'].equals(df['true_final_ride_cost']))

True

На вход подается: Переменная df  с полным DataFrame с исходными данными.
На выходе принимается: Измененный DataFrame (переменная df).

# Задача на 3-ем шаге урока

**🧠 Задача: 🖐 gold фичей**

Задача:

Создайте новый датафрейм, в котором для каждой машины есть следующие столбцы:

- Столбец feature_1 - Количество уникальных значений остановок (stop_times).
- Столбец feature_2 - Второй максимум столбца максимальной скорости (speed_max).
- Столбец feature_3 - Отношение минимального и максимального значения рейтинга.
- Столбец feature_4 - Самое популярное значение числа остановок (другим словами, мода).
- Столбец feature_5 - Стандартное отклонение стоимостей поездок (ride_cost).

Решение запишите в переменную result.

In [42]:
import numpy as np
import pandas as pd

df = pd.read_csv('https://stepik.org/media/attachments/lesson/779916/3_1_3.csv')

# В переменной ans находится правильный ответ для df
ans = pd.read_csv('https://stepik.org/media/attachments/lesson/779916/3_1_3_ans.csv')
ans.head()

       car_id  feature_1   feature_2  feature_3  feature_4      feature_5
0  G-1056464Y          5   96.000000   0.299279          1  125833.828153
1  M15952724y          4  151.000000   0.054645          0   26887.711194
2  M50269450O          8  115.597945   0.241451          0  136560.952417
3  Z16920973J          4   94.167306   0.216853          0   65036.154948
4  q-1127410X          3  137.914456   0.110429          0   90794.737314

In [43]:
result = df.groupby('car_id', as_index=False).agg(
    feature_1 = ('stop_times', 'nunique'),
    feature_2 = ('speed_max', lambda x: sorted(x)[-2]),
    feature_3 = ('rating', lambda x: min(x) / max(x)),
    feature_4 = ('stop_times', lambda x: x.mode()[0]),
    feature_5 = ('ride_cost', 'std')
)
result

       car_id  feature_1   feature_2  feature_3  feature_4      feature_5
0  G-1056464Y          5   96.000000   0.299279          1  125833.828153
1  M15952724y          4  151.000000   0.054645          0   26887.711194
2  M50269450O          8  115.597945   0.241451          0  136560.952417
3  Z16920973J          4   94.167306   0.216853          0   65036.154948
4  q-1127410X          3  137.914456   0.110429          0   90794.737314
5  z-2033330g          4  120.153166   0.011820          0     460.271690
6  z48466812V          4  139.000000   0.085864          0   16101.650675

На вход подается: Переменная df  с исходными данными.
На выходе принимается: Переменная result.

# Задача на 4-ом шаге урока

**🧠 Задача на merge()**

Задача:
- Обогатите датасет rides про поездки информацией о будущем виде поломки, используя датасет cars.
- Удалите лишние столбцы. Таблицу rides надо дополнить лишь столбцом target_class.
- Удалите поездки, для которых нет информации про поломки.  
- Запишите в переменную result.

In [44]:
import pandas as pd

rides = pd.read_csv('https://stepik.org/media/attachments/lesson/779916/3_1_4_rides.csv')
cars = pd.read_csv('https://stepik.org/media/attachments/lesson/779916/3_1_4_cars.csv')

# В переменную ans записан правильный ответ, с которым можно сверить свое решение.
ans = pd.read_csv('https://stepik.org/media/attachments/lesson/779916/3_1_4_ans.csv')
ans.head()

       car_id ride_id  rating  ride_duration  ride_cost     target_class
0  L-1156474z     u1g    5.81             33        391        break_bug
1  M20797256F     e1V    5.01             56        667  engine_overheat
2  E16896376o     B1Q    4.88             26        228  engine_overheat
3  X10754765V     M1i    1.62             29        312      electro_bug
4  E16896376o     V1L    6.98             37        512  engine_overheat

На выходе принимается: Переменная result

In [45]:
cols = ['car_id', 'target_class']
result = rides.merge(cars[cols], on='car_id', how='left').dropna(subset='target_class')
result.head()

        car_id ride_id  rating  ride_duration  ride_cost     target_class
7   L-1156474z     u1g    5.81             33        391        break_bug
17  M20797256F     e1V    5.01             56        667  engine_overheat
18  E16896376o     B1Q    4.88             26        228  engine_overheat
21  X10754765V     M1i    1.62             29        312      electro_bug
28  E16896376o     V1L    6.98             37        512  engine_overheat

# Задача на 5-ом шаге урока

**🧠 Задача на transform() и 3 silver фичи**

На вход подается: Переменная rides с исходными данными про поездки.

Задача:

- Обогатите датасет rides про поездки дополнительными признаками без использования метода merge.
- Добавьте столбец car_ride_count - общее число поездок для этой машины.
- Добавьте столбец user_rating_max - максимальный рейтинг, поставленный этим пользователем.
- Добавьте столбец user_ride_cost_mean - средняя стоимость поездки этого пользователя.
- Результат запишите в переменную result.

In [46]:
import numpy as np
import pandas as pd

rides = pd.read_csv('https://stepik.org/media/attachments/lesson/779916/3_1_5.csv')

# В столбцах true_car_ride_count, true_user_rating_max, true_user_ride_cost_mean записаны правильные ответы.
# Создайте столбцы car_ride_count, user_rating_max, user_ride_cost_mean

In [47]:
rides['car_ride_count'] = rides.groupby('car_id')['car_id'].transform('count').astype('int64')
rides['user_rating_max'] = rides.groupby('user_id')['rating'].transform('max')
rides['user_ride_cost_mean'] = rides.groupby('user_id')['ride_cost'].transform('mean')

In [48]:
# Проверить корректность своего решения можно, например, таким способом
print(rides['true_car_ride_count'].equals(rides['car_ride_count']))
print(rides['true_user_rating_max'].equals(rides['user_rating_max']))
print(rides['true_user_ride_cost_mean'].equals(rides['user_ride_cost_mean']))

True
True
True

На выходе принимается: Переменная result.

In [49]:
result = rides.copy()

# Задача на 6-ом шаге урока

**🧠 Задача на transform() и 4 самописные функции**

На вход подается: Переменная rides  с исходными данными про поездки.

Задача

- Обогатите датасет rides про поездки дополнительными признаками без использования метода merge.
- Добавьте столбец feature_1 — 75% перцентиль столбца ride_cost для каждого пользователя (user_id).
- 🎃 Добавьте столбец feature_2 — разницу максимального и минимального значения rating, деленную на среднее столбца rating для каждого пользователя (user_id).
- 👽 Добавьте столбец feature_3  — количество значений ride_duration, которое больше 40 для каждой машины (car_id).
- 👾 Добавьте столбец feature_4 — сумму значений ride_duration, которая больше 40 для каждой машины (car_id).
- Результат запишите в переменную result.

In [50]:
import pandas as pd

rides = pd.read_csv('https://stepik.org/media/attachments/lesson/779916/3_1_6.csv')

# В столбцы true_feature_1, true_feature_2, true_feature_3, true_feature_4 записаны правильные ответы
# Создайте столбцы feature_1, feature_2, feature_3, feature_4.

In [51]:
transform_function1 = lambda x: x.quantile(0.75) # True
transform_function2 = lambda x: (x.max() - x.min()) / x.mean() # False
transform_function3 = lambda x: (x > 40).sum() # True
transform_function4 = lambda x: x[x > 40].sum() # True

rides['feature_1'] = rides.groupby('user_id', as_index=False)['ride_cost'].transform(transform_function1)
rides['feature_2'] = rides.groupby('user_id', as_index=False)['rating'].transform(transform_function2)
rides['feature_3'] = rides.groupby('car_id', as_index=False)['ride_duration'].transform(transform_function3)
rides['feature_4'] = rides.groupby('car_id', as_index=False)['ride_duration'].transform(transform_function4)

In [52]:
# Проверить корректность своего решения можно, например, таким способом
print(rides['true_feature_1'].equals(rides['feature_1']))
print(rides['true_feature_2'].equals(rides['feature_2']))
print(rides['true_feature_3'].equals(rides['feature_3']))
print(rides['true_feature_4'].equals(rides['feature_4']))

True
False
True
True

На выходе принимается: Переменная result

In [53]:
result = rides.copy()

# Задача на 7-ом шаге урока

**🧠 Задача на pivot_table() и merge()**

Задача. На основе этого датафрейма надо будет собрать несколько сводных таблиц (pivot table) и потом смержить их в одну итоговую, получив некое подобие эмбеддингов для подачи в модель.

- Индексом во всех таблицах будет user_id.
- 🙂 Первая таблица: Сколько раз пользователь брал машины определенного класса?
- 🙃 Вторая таблица: Какими были максимальная, минимальная и средняя дистанция и стоимость поездки пользователя?
- 🙂 Третья таблица: Сколько уникальных машин брал пользователь в аренду?
- Далее соединяем по ключу (смерживаем) все 3 таблицы в одну.
- И в конце добавляем бинарный таргет в столбец crazy_driver: Является ли наш пользователь безумным гонщиком? Если его максимальная скорость превышала 100 км/ч, то 1; если не превышала, то 0.
- Результат решения запишите в переменную result.

In [54]:
import pandas as pd

df = pd.read_csv('https://stepik.org/media/attachments/lesson/779916/3_1_7.csv')

# В ans записан правильный ответ
ans = pd.read_csv('https://stepik.org/media/attachments/lesson/779916/3_1_7_ans.csv')
ans.head()

,user_id,economy_count,standart_count,distance_min,ride_cost_min,distance_max,ride_cost_max,distance_mean,ride_cost_mean,car_id_nunique,crazy_driver
0,A11173530w,1.0,0.0,2.967598e+03,614,2.967598e+03,614,2.967598e+03,614,1,1
1,A66187474K,0.0,1.0,4.621773e+03,1320,4.621773e+03,1320,4.621773e+03,1320,1,0
2,C84438702e,1.0,0.0,1.221070e+03,195,1.221070e+03,195,1.221070e+03,195,1,1
3,E15036556k,0.0,1.0,1.284249e+06,374394,1.284249e+06,374394,1.284249e+06,374394,1,0
4,G84350611k,0.0,1.0,1.850353e+03,428,1.850353e+03,428,1.850353e+03,428,1,0

In [55]:
crazy_driver_df = df.pivot_table(
    index='user_id',
    values='speed_max',
    aggfunc='max'
).assign(crazy_driver=lambda x: (x['speed_max'] > 100).astype(int))[['crazy_driver']]

pivot_table1 = df.pivot_table(
    index='user_id',
    columns=['car_type'],
    values=['model'],
    aggfunc=['count']
).fillna(0)

pivot_table2 = df.pivot_table(
    index='user_id',
    values=['distance', 'ride_cost'],
    aggfunc=['min', 'max', 'mean']
).fillna(0)

pivot_table3 = df.pivot_table(
    index='user_id',
    values=['car_id'],
    aggfunc=['nunique']
).fillna(0)

pivot_table1.columns = [f'{i[2]}_{i[0]}' for i in pivot_table1.columns]
pivot_table2.columns = [f'{i[1]}_{i[0]}' for i in pivot_table2.columns]
pivot_table3.columns = [f'{i[1]}_{i[0]}' for i in pivot_table3.columns]

result = pivot_table1.merge(pivot_table2, on='user_id') \
                     .merge(pivot_table3, on='user_id') \
                     .merge(crazy_driver_df, on='user_id')

result = result.reset_index()
result.head()

,user_id,economy_count,standart_count,distance_min,ride_cost_min,distance_max,ride_cost_max,distance_mean,ride_cost_mean,car_id_nunique,crazy_driver
0,A11173530w,1.0,0.0,2.967598e+03,614,2.967598e+03,614,2.967598e+03,614.0,1,1
1,A66187474K,0.0,1.0,4.621773e+03,1320,4.621773e+03,1320,4.621773e+03,1320.0,1,0
2,C84438702e,1.0,0.0,1.221070e+03,195,1.221070e+03,195,1.221070e+03,195.0,1,1
3,E15036556k,0.0,1.0,1.284249e+06,374394,1.284249e+06,374394,1.284249e+06,374394.0,1,0
4,G84350611k,0.0,1.0,1.850353e+03,428,1.850353e+03,428,1.850353e+03,428.0,1,0

Результат решения запишите в переменную result

Комментарий: Не забывайте избавляться от мультииндекса и использовать pivot_table. Использовать groupby нельзя! Пропуски заполнять 0.